### ISSUE TITLE
[Other] Community Exchange Introduction/Tracking

### ISSUE THREAD

**Issue by ericdrosado** [Kipper-Lang/Kipper#103]
### Is there an existing proposal for this?

- [X] I have searched the existing issues

### This feature does not exist in the latest version

- [X] I am using the latest version

### Proposal

👋 Hi @Luna-Klatzer ,

I am your GitHub mentor for the GitHub Education, [Community Exchange](https://airtable.com/shrRJ3AvEZQohOdGV) (CX) project. I'll be collaborating with you on preparing your repo for CX. 

You mentioned in your submission that you wanted to submit a `Collaborate` repo. This means that you want to invite other students to collaborate and add features to this repo. 

After reviewing your repository, it is already in great shape! 🎉  We will be accepting submissions on June 1, 2022. Before then I would recommend:

- [x]  Adding a  how to [contribute to your project](https://docs.github.com/en/get-started/quickstart/contributing-to-projects) in the README
- [x] Add a [CONTRIBUTING.md](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors).
 
If you have any questions, please feel free to leave a comment, otherwise, I will contact you when it is time to submit your project! :octocat:

**Comment by ericdrosado** [comment]
Thanks for adding the recommended changes @Luna-Klatzer. 🚀  I will contact you next week on how to submit your project to Community Exchange. 

Please let me know if you have any questions or concerns.
